twig:
    default_path: '%kernel.project_dir%/templates'
    #activation bootstrap sur les formulaires
    form_theme: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
