twig:
    default_path: '%kernel.project_dir%/templates'
    #activation bootstrap sur les formulaires
    form_theme: ['bootstrap_5_layout.html.twig']

    globals:
        site_name: 'Le blog de batman'
        google_recaptcha_site_key: '%env(GOOGLE_RECEPTCHA_SITE_KEY)%'

when@test:
    twig:
        strict_variables: true
